//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRecall
    {
        public string DocumentNo { get; set; }
        public string LeaveDocumentNo { get; set; }
        public int LeaveDaysRecalled { get; set; }
        public string EmployeeNo { get; set; }
        public string ApprovalStatus { get; set; }
    
        public virtual Leaf Leaf { get; set; }
    }
}
